# Configuration file for TravisCI

language: c

os: linux
dist: bionic

# Only build pushes to the master branch and tags. This avoids the double
# builds than happen when working on a branch instead of a fork.
branches:
    only:
        - master
        # Regex to build tagged commits with version numbers
        - /\d+\.\d+(\.\d+)?(\S*)?$/

env:
    global:
        # GMT install location
        - GMT_INSTALL_DIR=${HOME}/gmt-install-dir
        - PATH=${GMT_INSTALL_DIR}/bin:${PATH}

addons:
  apt:
    packages:
      - cmake
      - build-essential
      - libcurl4-gnutls-dev
      - libnetcdf-dev
      - libgdal-dev
      - libfftw3-dev
      - libpcre3-dev
      - liblapack-dev
      - curl

before_install:
    # Install GMT master branch
    - curl https://raw.githubusercontent.com/GenericMappingTools/gmt/master/ci/build-gmt-master.sh | bash
    # Check GMT installation
    - gmt --version
    - gmt-config --all

install:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - cd ..

script:
    - gmt set GMT_CUSTOM_LIBS ${PWD}/build/src/plugins/custom.so
    - gmt --version -Vd
    - gmt average

notifications:
    email: false
