/* $Id$
 *
 * Copyright (c) 2016-2018 by pwessel
 * See LICENSE.TXT file for copying and redistribution conditions.
 */

/* gmt_custom_module.h declares the prototypes for custom module functions
 * and the array that contains custom GMT module parameters such as name
 * and purpose strings.
 * DO NOT edit this file directly! Regenerate the file by running
 *	 gmt_make_custom_code.sh
 */

#pragma once
#ifndef _GMT_CUSTOM_MODULE_H
#define _GMT_CUSTOM_MODULE_H

#ifdef __cplusplus /* Basic C++ support */
extern "C" {
#endif

/* Declaration modifiers for DLL support (MSC et al) */
#include "declspec.h"

/* Prototypes of all modules in the GMT custom library */
EXTERN_MSC int GMT_gmtaverage (void *API, int mode, void *args);
EXTERN_MSC int GMT_gmtmercmap (void *API, int mode, void *args);
EXTERN_MSC int GMT_gmtparser (void *API, int mode, void *args);
EXTERN_MSC int GMT_grdfourier (void *API, int mode, void *args);

/* Pretty print all modules in the GMT custom library and their purposes */
EXTERN_MSC void gmt_custom_module_show_all (void *API);
/* List all modules in the GMT custom library to stdout */
EXTERN_MSC void gmt_custom_module_list_all (void *API);
/* Function called by GMT_Encode_Options so developers can get information about a module */
EXTERN_MSC const char * gmt_custom_module_info (void *API, char *candidate);

#ifdef __cplusplus
}
#endif

#endif /* !_GMT_CUSTOM_MODULE_H */
